CU.HouseHolding/Controllers/BulkUploadController.cs
using CU.HouseHolding.DataAccess;
using CU.HouseHolding.DataAccess.Model;
using Hangfire;
using Newtonsoft.Json;
using System;
using System.IO;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
namespace CU.HouseHolding.Controllers
{
    public class BulkUploadController : BaseController
    {
        public BulkUploadController()
        { }
        // GET: BulkUpload
        public ActionResult Index()
        {
            // var user = CurrentProfile.LoggedUserProfile;
            //Functions objcontrl = new Functions();
            //objcontrl.SendAlertNotificationAsync();
            //BackgroundJob.Enqueue(() => objcontrl.SendAlertNotificationAsync());
            //ImportedFileService fileService = new ImportedFileService();
            //fileService.ProcessFile(7);
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form, HttpPostedFileBase postedFile)
        {
            using (var ts = new TransactionScope())
            {
                try
                {
                    ImportedFileService fileService = new ImportedFileService();
                    var result = fileService.CheckReportExist(form["ReportName"]);
                    if (result == true)
                    {
                        ts.Dispose();
                        TempData["Error"] = "Please enter Diffrent Report Name";
                    }
                    else
                    {
                        string slidervalue = form["listenSlider"];
                        HttpFileCollectionBase files = Request.Files;
                        for (int i = 0; i < files.Count; i++)
                        {
                            HttpPostedFileBase file = files[i];
                            if (file.FileName.EndsWith(".xls") || file.FileName.EndsWith(".csv") || file.FileName.EndsWith(".xlsx"))
                            {
                                FileInfo fi = new FileInfo(file.FileName);
                                string Path = Server.MapPath("~/App_Data/UploadedFiles");
                                string SaveFileName = Path + "\\" + DateTime.Now.ToString("ddMMyyyyhhmmss") + "_" + fi.Name;
                                if (!Directory.Exists(Path))
                                {
                                    Directory.CreateDirectory(Path);
                                }
                                file.SaveAs(SaveFileName);
                                //Store File Master Record

                                ImportedFileMaster importedFileMaster = new ImportedFileMaster();
                                importedFileMaster.CreatedDate = DateTime.UtcNow;
                                importedFileMaster.FileName = fi.Name;
                                importedFileMaster.ReportName = form["ReportName"];
                                importedFileMaster.SimilarityScore = Convert.ToInt32(slidervalue);
                                importedFileMaster.UserId = Convert.ToInt32(Session["UserID"].ToString());
                                fileService.ImportedFileMaster_InsertOrUpdate(importedFileMaster);
                                //store Details file records 
                                fileService.StoreFiledatatoDB(fi.Name, SaveFileName, importedFileMaster.Id);
                                // Put the Algorithm to run in Background
                                //fileService.ProcessFile(importedFileMaster.Id);
                                BackgroundJob.Enqueue(() => fileService.ProcessFile(importedFileMaster.Id));
                                //return Json(fi.Name, JsonRequestBehavior.AllowGet);
                                TempData["Message"] = "File Imported Successfully and we have started our HousHolding Algorithm to processs. You will be notified via Email once report is ready";
                                ts.Complete();
                                return View();
                            }
                            else
                            {
                                TempData["Error"] = "Invalid File Type";
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    ts.Dispose();
                    TempData["Error"] = ex.Message;
                }
            }
            return View();
        }
        public ActionResult ValidateFile()
        {
            string FileName = "";
            HttpFileCollectionBase files = Request.Files;
            for (int i = 0; i < files.Count; i++)
            {
                HttpPostedFileBase file = files[i];
                string fname;

                // Checking for Internet Explorer    
                if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                {
                    string[] testfiles = file.FileName.Split(new char[] { '\\' });
                    fname = testfiles[testfiles.Length - 1];
                }
                else
                {
                    fname = file.FileName;
                    FileName = file.FileName;
                }

                // Get the complete folder path and store the file inside it.    
                fname = Path.Combine(Server.MapPath("~/App_Data/UploadedFiles/"), fname);
                file.SaveAs(fname);
                ImportedFileService fs = new ImportedFileService();
                var result = fs.ValidateFile(new FileInfo(file.FileName).Name, fname);
                var converted = JsonConvert.SerializeObject(result.Message, Formatting.None);
                return Json(converted, JsonRequestBehavior.AllowGet);
            }

            return Json(FileName, JsonRequestBehavior.AllowGet);
        }

        #region Custom Mapping
        public ActionResult CustomMapping()
        {
            CustomMappingservices cs = new CustomMappingservices();
            CustomMappingViewModel model = new CustomMappingViewModel();
            model.ReportNames = cs.ReportNames();
            model.Cities = cs.Cities();
            model.States = cs.States();
            model.Zipcodes = cs.ZipCodes();
            //model.HouseHoldIds = new List<string>(); //cs.HouseHoldingIds(Request.Form["ReportNames"] == null ? "" : Request.Form["ReportNames"].ToString());
            //model.UnAllocatedMemberIds = cs.UnAllocatedMembers();
            ViewBag.SelectedName = "All Reports";
            ViewBag.SelectedCityName = "All Cities";
            ViewBag.SelectedStateName = "All States";
            ViewBag.SelectedZipcode = "All ZipCode";
            return View(model);
        }
        public JsonResult GetUnAllocateMembersList(int pageCount, int takeCount)

        {
            CustomMappingservices cs = new CustomMappingservices();
            var lstmembers = cs.UnAllocatedMembers(pageCount, takeCount);
            return Json(new { items = lstmembers }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetFilterMembersList(string searchText)
        {
            CustomMappingservices cs = new CustomMappingservices();
            var lstmembers = cs.UnAllocatedMembersbySearchText(searchText);
            if (lstmembers.Count == 0)
                lstmembers = null;
            return Json(new { results = lstmembers }, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult CustomMapping(CustomMappingViewModel model)
        {
            CustomMappingservices cs = new CustomMappingservices();
            ViewBag.SelectedName = model.ReportNames[0];
            ViewBag.SelectedCityName = model.Cities[0];
            ViewBag.SelectedStateName = model.States[0];
            ViewBag.SelectedZipcode = model.Zipcodes[0];
            model.ReportNames = cs.ReportNames();
            model.Cities = cs.Cities();
            model.States = cs.States();
            model.Zipcodes = cs.ZipCodes();
            model.HouseHoldIds = cs.HouseHoldingIds(Request.Form["ReportNames"].ToString(), Request.Form["Cities"].ToString(), Request.Form["States"].ToString(), Request.Form["Zipcodes"].ToString(), Request.Form["MemberName"].ToString(), Request.Form["HHId"].ToString());
            //model.UnAllocatedMemberIds = cs.UnAllocatedMembers();
            return View(model);
        }
        public ActionResult _MembersList(string HouseHoldId)
        {
            CustomMappingservices cs = new CustomMappingservices();
            CustomMappingViewModel model = new CustomMappingViewModel();
            model.MemberIds = cs.MembersbyHouseHold(HouseHoldId);
            ViewBag.HouseHoldId = HouseHoldId;
            if (Request.IsAjaxRequest())
            {
                return PartialView("_MembersList", model);
            }
            return View(model);
        }
        public ActionResult DeAllocateMember(string SelectedMembers, string HouseHoldId)
        {
            CustomMappingservices cs = new CustomMappingservices();
            cs.DeAllocateMembers(SelectedMembers, HouseHoldId);
            return Content("Success");
        }
        public ActionResult AllocateMember(string SelectedMembers, string HouseHoldId)
        {
            CustomMappingservices cs = new CustomMappingservices();
            cs.AllocateMembers(SelectedMembers, HouseHoldId);
            return Content("Success");
        }
        public ActionResult AllocateMemberwithNewHH(string SelectedMembers)
        {
            CustomMappingservices cs = new CustomMappingservices();
            var HHID = cs.AllocateMembersWithNewHH(SelectedMembers);
            return Content(HHID);
        }

        #endregion
    }
}

CU.HouseHolding/Views/BulkUpload/CustomMapping.cshtml
@model CU.HouseHolding.DataAccess.Model.CustomMappingViewModel
@{
    ViewBag.Title = "Custom Mapping";
    ViewBag.Page = "mapping";
}

<header class="page-header">
    <h2>Custom Mapping</h2>
    <style>
        * {
            box-sizing: border-box;
        }

        .chosen-container {
            width: 157px !important;
        }

        #myInput, #FilterMember {
            background-image: url('/css/searchicon.png');
            background-position: 10px 12px;
            background-repeat: no-repeat;
            width: 100%;
            font-size: 12px;
            padding: 12px 20px 12px 40px;
            border: 1px solid #ddd;
            margin-bottom: 12px;
        }

        #myUL {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

            #myUL li a {
                border: 1px solid #ddd;
                margin-top: -1px; /* Prevent double borders */
                background-color: #f6f6f6;
                padding: 12px;
                text-decoration: none;
                font-weight: bold;
                font-size: 12px;
                color: black;
                display: block
            }

                #myUL li a:hover:not(.header) {
                    background-color: #eee;
                }

        .custom-map__scroll-y {
            height: 300px;
            overflow-y: auto;
        }

        .custom-map-tbl__scroll-y {
            height: 270px;
            overflow-y: auto;
        }

        .tbl-col1 {
            width: 20px;
        }

        .mt-40 {
            margin-top: 40px;
        }
    </style>
    <link href="~/Content/chosen.css" rel="stylesheet" />


</header>
<div class="row" onload="showLoader(this);">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">
                @*<div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>*@

                <h2 class="panel-title"><span style="color:red;">Click on HouseHold Id to see its Members List</span></h2>
            </header>
            <div class="panel-body">
                @using (Html.BeginForm("CustomMapping", "BulkUpload", FormMethod.Post, new { @class = "form-horizontal form-bordered", enctype = "multipart/form-data", onsubmit = "showLoader(this);" }))
                {

                    <div class="form-group">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                Report : @Html.DropDownListFor(m => m.ReportNames, new SelectList(Model.ReportNames, ViewBag.SelectedName), "All Reports", new { @class = "chosen-select" })
                            </div>
                            <div class="col-md-3">
                                City : @Html.DropDownListFor(m => m.Cities, new SelectList(Model.Cities, ViewBag.SelectedCityName), "All Cities", new { @class = "chosen-select" })
                            </div>
                            <div class="col-md-3">
                                State : @Html.DropDownListFor(m => m.States, new SelectList(Model.States, ViewBag.SelectedStateName), "All States", new { @class = "chosen-select" })
                            </div>
                            <div class="col-md-3">
                                ZipCode : @Html.DropDownListFor(m => m.Zipcodes, new SelectList(Model.Zipcodes, ViewBag.SelectedZipcode), "All ZipCode", new { @class = "chosen-select" })
                            </div>
                        </div>
                        <div class="col-md-12" style="padding-top:15px;">

                            <div class="col-md-3">
                                Member Name: @Html.TextBoxFor(m => m.MemberName, new { @class = "form-control", @style = "width:157px;" })
                            </div>
                            <div class="col-md-2">
                                HouseHoldId :@Html.TextBoxFor(m => m.HHId, new { @class = "form-control", @style = "width:157px;" })
                            </div>
                            <div class="col-md-2">
                                <button type="submit" class="mb-xs mt-xs mr-xs btn btn-primary">Search</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-3">
                            @Html.Partial("_HouseHoldList", Model)
                        </div>
                        <div class="col-md-5" id="detailsDiv">
                        </div>
                        @*<div class="col-md-4">
                                @Html.Partial("_UnAllocatedMembersList", Model)
                            </div>*@
                        <div class="col-md-4">
                            <h4 class="mt-40">UnAllocated Members</h4>

                            <input type="text" id="FilterMember" onkeyup="LoadFilterData()" placeholder="Search for Member.." title="Type in a name">
                            <div id="result" class="custom-map-tbl__scroll-y">

                            </div>
                            <div class="input-group" id="dvaddmore" style="margin-top: 15px;">
                                <input type="button" id="allocate" name="search" value="Allocate Selected" class="form-control btn btn-primary">
                            </div>
                            <div class="input-group" id="dvaddmore" style="margin-top: 15px;">
                                <input type="button" id="allocatewithnewHH" name="search" value="Allocate Selected With New HouseHold" class="form-control btn btn-primary">
                            </div>
                        </div>
                    </div>
                }
            </div>
        </section>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/chosen.jquery.min.js"></script>
    <script>
        var pageCount = 1; // start at 26th record (assumes first 25 included in initial view)
        var takeCount = 1000; // return new 25 records
        var hasMoreRecords = true;
        $(document).ready(function () {
            $(".chosen-select").chosen();
            LoadData();

        });

        //$("#result").scroll(function () {
        //    if ($(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight) {
        //        //$("span").show();
        //        //alert('recahed');
        //        LoadFilterData();
        //    } else {
        //        //$("span").hide();
        //    }
        //});

        function LoadData() {

            //if (pageCount > 1) {
            //    $('#result tr#btnrow').remove();
            //}
            if (!hasMoreRecords) {

                return;
            }
            var mytable = $('<table class="table table-bordered table-striped table-condensed mb-none"></table>');
            $('<thead><tr><td class="tbl-col1"><input type="checkbox" id="chkallunallocated" onclick="UnchkAllocated(this);"></input></td><td>Member</td></tr></thead>').appendTo(mytable);
            $.ajax({
                url: "/BulkUpload/GetUnAllocateMembersList",
                data: { pageCount: 1, takeCount: takeCount },
                dataType: "json",
                type: "GET",
                success: function (data) {
                    if (data === null) {
                        hasMoreRecords = false; // signal no more records to display

                    }
                    else {
                        $.each(data.items, function (index, item) {
                            //var container = $('<table></table>');
                            $('<tr><td><input type="checkbox" id=' + data.items[index].Id + '></input></td><td>' + data.items[index].Memberid + ' - '+ data.items[index].FirstName + ' ' + data.items[index].LastName + '</td></tr>').appendTo(mytable);

                        });
                        //if (data.items.length != 0) {
                        //    $('<tr id="btnrow"><td colspan="2"><input type="button" id="btnLoadMore" onclick="LoadData();" value="Load More"></input></td></tr>').appendTo(mytable);
                        //}
                        mytable.appendTo("#result");
                        pageCount += 1; // update for next iteration
                    }
                    //alert(data.items[index].FirstName);
                    //alert('test');
                },
                error: function (xhr) {
                    alert('Error: ' + xhr.statusText);
                }
            });
        }
        function LoadFilterData() {
            $("#result").empty();

            if ($('#FilterMember').val() == '') {
                LoadData();
            }
            else {
                var mytable = $('<table class="table table-bordered table-striped table-condensed mb-none"></table>');
                $('<thead><tr><td class="tbl-col1"><input type="checkbox" id="chkallunallocated" onclick="UnchkAllocated(this);"></input></td><td>Member</td></tr></thead>').appendTo(mytable);
                $.ajax({
                    url: "/BulkUpload/GetFilterMembersList",
                    data: { searchText: $('#FilterMember').val() },
                    dataType: "json",
                    type: "GET",
                    success: function (data) {

                        if (data === null) {
                            alert('t');
                            return; // signal no more records to display
                        }
                        else {
                            $.each(data.results, function (index, item) {
                                //var container = $('<table></table>');
                                $('<tr><td><input type="checkbox" id=' + data.results[index].Id + '></input></td><td>' + data.items[index].Memberid + ' - ' + data.items[index].FirstName + ' ' + data.items[index].LastName + '</td></tr>').appendTo(mytable);

                            });
                            // $('<tr id="btnrow"><td colspan="2"><input type="button" id="btnLoadMore" onclick="LoadData();" value="Load More"></input></td></tr>').appendTo(mytable);
                            mytable.appendTo("#result");

                        }
                        //alert(data.items[index].FirstName);
                        //alert('test');
                    },
                    error: function (xhr) {
                        alert('Error: ' + xhr.statusText);
                    }
                });
            }
        }


        function UnchkAllocated(data) {
            $('#result input:checkbox').not(data).prop('checked', data.checked);
        }

        $("#allocate").click(function () {

            if ($('#hdnHouseHoldId').val() == undefined || $('#hdnHouseHoldId').val() == '') {
                alert('Please select any HouseHold First');
                return false;
            }
        var Selectedid = "";
            $("#result input:checkbox:checked").each(function () {

            Selectedid += $(this).attr("id") + ",";
        });
            if (Selectedid == '') {
                alert('Please select any Member First');
                return false;
            }

        $.ajax({
            url: '@Url.Action("AllocateMember")',
            type: 'POST',
            data: { 'SelectedMembers': Selectedid, 'HouseHoldId': $('#hdnHouseHoldId').val()},
            error: function (xhr) {
                alert('Error: ' + xhr.statusText);

            },
            success: function (result) {
                //alert(result);
                //$('#detailsDiv').html(result);
                GetMembers($('#hdnHouseHoldId').val());
                LoadFilterData();
            }
        });
        });

        $("#allocatewithnewHH").click(function () {

            //if ($('#hdnHouseHoldId').val() == undefined || $('#hdnHouseHoldId').val() == '') {
            //    alert('Please select any HouseHold First');
            //    return false;
            //}
        var Selectedid = "";
            $("#result input:checkbox:checked").each(function () {

            Selectedid += $(this).attr("id") + ",";
        });
            if (Selectedid == '') {
                alert('Please select any Member First');
                return false;
            }

        $.ajax({
            url: '@Url.Action("AllocateMemberwithNewHH")',
            type: 'POST',
            data: { 'SelectedMembers': Selectedid},
            error: function (xhr) {
                alert('Error: ' + xhr.statusText);

            },
            success: function (result) {
                alert('Selected Members assigned with New HouseHold - ' +result);
                //$('#detailsDiv').html(result);
                $("#myUL p").remove();
                //GetMembers($('#hdnHouseHoldId').val());
                
                $('#myUL li:eq(0)').before("<li><a href='#' onclick=\"GetMembers('" + result + "', false)\">" + result+"</a></li>");
                LoadFilterData();
            }
        });
    });
    </script>
}

CU.HouseHolding/Views/BulkUpload/Index_Ajax.cshtml
@*@{
        Layout = null;
    }*@
<link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
      rel="stylesheet">   @*I got this link from Tutorials point*@
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <style>
        .ui-widget-header {
            background: #cedc98;
            border: 1px solid #DDDDDD;
            color: #333333;
            font-weight: bold;
        }

        .progress-label {
            position: absolute;
            left: 50%;
            top: 13px;
            font-weight: bold;
            text-shadow: 1px 1px 0 #fff;
        }

        .red {
            color: red;
        }
    </style>
    <div class="container">
        <h1>
            File Upload Demo
        </h1>
        <div id="FileBrowse">
            <div class="row">
                <div class="col-sm-4">
                    <input type="file" id="Files" />
                </div>
                <div class="col-sm-2">
                    <input type="button" id="UploadBtn" class="btn btn-danger" value="Upload" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div id="progressbar-5">
                    <div class="progress-label">
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row" id="Message">
             
        </div>
        <br />
        <br />
        <br />
        <br />
    </div>

    @section scripts{
        <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
        <script src="https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
        <script>


        $('#UploadBtn').click(function () {

            var fileUpload = $("#Files").get(0);
            var files = fileUpload.files;
            // Create FormData object
            var fileData = new FormData();
            // Looping over all files and add it to FormData object
            for (var i = 0; i < files.length; i++) {
                fileData.append(files[i].name, files[i]);
            }
            $.ajax({
                url: '/BulkUpload/UploadFiles',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                async: false,
                success: function (result) {
                    if (result != "") {
                        $('#FileBrowse').find("*").prop("disabled", true);
                        LoadProgressBar(result); //calling LoadProgressBar function to load the progress bar.
                    }
                },
                error: function (err) {
                    alert(err.statusText);
                }
            });

        });

        function LoadProgressBar(result) {
            var progressbar = $("#progressbar-5");
            var progressLabel = $(".progress-label");
            progressbar.show();
            $("#progressbar-5").progressbar({
                //value: false,
                change: function () {
                    progressLabel.text(
                     progressbar.progressbar("value") + "%");  // Showing the progress increment value in progress bar
                },
                complete: function () {
                    progressLabel.text("Loading Completed!");
                    progressbar.progressbar("value", 0);  //Reinitialize the progress bar value 0
                    progressLabel.text("");
                    progressbar.hide(); //Hiding the progress bar
                    //var markup = "<tr><td>" + result + "</td><td><a href='#' onclick='DeleteFile(\"" + result + "\")'><span class='glyphicon glyphicon-remove red'></span></a></td></tr>"; // Binding the file name
                    //$("#ListofFiles tbody").append(markup);
                    $('#Message').text('File Imported Successfully and we have started our HousHolding Algorithm to processs. once its done we will update you via Email to check the report');
                    $('#Files').val('');
                    $('#FileBrowse').find("*").prop("disabled", false);
                }
            });
            function progress() {
                var val = progressbar.progressbar("value") || 0;
                progressbar.progressbar("value", val + 1);
                if (val < 99) {
                    setTimeout(progress, 25);
                }
            }
            setTimeout(progress, 100);
        }

        function DeleteFile(FileName) {

        //Write your delete logic here
        }

        </script>
    }

CU.HouseHolding/Views/BulkUpload/_HouseHoldList.cshtml
@model CU.HouseHolding.DataAccess.Model.CustomMappingViewModel

@if (Model.HouseHoldIds != null)
{
    <h2>HouseHoldId</h2>

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for HouseHoldId.." title="Type HouseHoldId">

    <ul id="myUL" class="custom-map__scroll-y">
        @if (Model.HouseHoldIds.Count > 0)
        {
            foreach (var item in Model.HouseHoldIds)
            {
                <li><a href="#" onclick="GetMembers('@item',false);">@item</a></li>
            }
        }
        else
        {
            <p style="color:red;">No Data Found</p>}

    </ul>
}
<script>
    function myFunction() {
        var input, filter, ul, li, a, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        ul = document.getElementById("myUL");
        li = ul.getElementsByTagName("li");
        for (i = 0; i < li.length; i++) {
            a = li[i].getElementsByTagName("a")[0];
            txtValue = a.textContent || a.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                li[i].style.display = "";
            } else {
                li[i].style.display = "none";
            }
        }
    }
    function GetMembers(HHId,LoadUnAllocateList) {
        $.ajax({
            url: '@Url.Action("_MembersList")?HouseHoldId=' + HHId,
            type: 'GET',
            error: function (xhr) {
                alert('Error: ' + xhr.statusText);

            },
            success: function (result) {

                $('#detailsDiv').html(result);
                $("#allocate").prop('value', 'Allocate Selected to ' + HHId); 
                if (LoadUnAllocateList) {
                    LoadFilterData();
                }
            }
        });
    }
</script>

CU.HouseHolding/Views/BulkUpload/_UnAllocatedMembersList.cshtml
@model CU.HouseHolding.DataAccess.Model.CustomMappingViewModel

@if (Model.UnAllocatedMemberIds != null)
{
    <h4 class="mt-40">UnAllocated Members</h4>

    <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for HouseHoldId.." title="Type in a name">

    <ul id="myUL" class="custom-map__scroll-y">
        @if (Model.UnAllocatedMemberIds.Count > 0)
        {
            foreach (var item in Model.UnAllocatedMemberIds)
            {
                <li><a href="#">@item.Memberid - @item.FirstName @item.LastName</a></li>
            }
        }
        else
        {
            <p style="color:red;">No Data Found</p>}

    </ul>
}